import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const pw = require('/opt/node22/lib/node_modules/playwright');
const SP = process.argv[2];
const browser = await pw.chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
await page.goto('http://localhost:5173/');
await page.evaluate(() => localStorage.setItem('potluck.save.v1', JSON.stringify({ version: 1, tripsCompleted: 1, coins: 500, upgrades: ['catHammock', 'railNets'], hatColor: 0x1f5c66, photos: [], buff: 'warmBellies', finds: { boot: true, bell: true, lore: [1] }, lastTrip: null })));
await page.goto('http://localhost:5173/');
await page.waitForTimeout(3500);
await page.screenshot({ path: SP + '/m8-chart.png' });
await page.click('[data-go]');
await page.waitForTimeout(2500);
const st = await page.evaluate(() => { const g = window.__game; return { up: [...g.ctx.upgrades], buffs: [...g.ctx.buffs], phase: g.trip.phase, paused: g.loop.paused, hat: g.crew.player.view.hat.userData.mat.color.getHex().toString(16) }; });
console.log(JSON.stringify(st));
await page.evaluate(() => localStorage.clear());
await page.goto('http://localhost:5173/');
await page.waitForTimeout(3000);
await page.screenshot({ path: SP + '/m8-title.png' });
await browser.close();
